name: basic node setup

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  node-lint-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-10.15]
        node: [18, 20, 22]

    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: install node_modules
        run: npm ci

      - name: node lint
        run: npm lint

      - name: node test
        run: npm test

    # - name: bundle test
    #   run:
    #     npx react-native bundle --entry-file packages/mobile/index.js --bundle-output /dev/null
